//webpage titles - all pages that display html/handlebars
var pgTitle = {
    home: 'Welcome to EqualityPay!',
    thanks: 'Confirming your email!',
    confirm: 'We are ready to go!',
    dosurvey: 'Please fill out the form',
    shosurvey: 'Your survey results',
    resubmit: 'Re-confirm your email',
    returnuser: 'You\'ve been here before!',
};
exports.getPgTitle = function(page) {
    return pgTitle[page];
};
// Parameters for select boxes, except states - dosurvey.handlebars
var ageRange = ['under 20', '21 to 25', '26 to 35', '35 to 45', '46 to 55', '56 to 64', 'over 65'];
var gender = ['female', 'male', 'gender neutral', 'gender non-conforming'];
var empDuration = ['less than 6 mos', '6 mos to 1 yr', '1 to 2 yrs', '2 to 5 yrs', '5 to 15 yrs', '15 to 25 yrs', 'over 25 yrs'];
var empSalary = ['<= $10,000', '$20,000', '$30,000', '$40,000', '$50,000',
    '$60,000', '$70,000', '$80,000', '$90,000', '$100,000', '>= $110,000'
];
var ethnicity = ['White', 'Black', 'Native American/Alaskan', 'Chinese', 'Japanese', 'Filipino', 'Korean', 'Asian Indian', 'Vietnamese',
    'Other East Asian', 'Middle Eastern', 'North African', 'South African', 'Pacific Islander', 'Mexican', 'Cuban', 'Puerto Rican', 'South/Central American', 'Other Hispanic'
];

var rngField = ['ageRange', 'gender', 'empDuration', 'empSalary'];
var rngObj = [ageRange, gender, empDuration, empSalary];
var reqField = ['employer', 'empState', 'empTitle', rngField[0], rngField[1], rngField[2], rngField[3]];
var nonReqField = ['userName', 'ethnicity'];

// for the survey form results display page - shosurvey.handlebars
var resDisp = {
    map: ['email', nonReqField[0], rngField[0], rngField[1], nonReqField[1], reqField[0], reqField[1], reqField[2],
        rngField[2], rngField[3]
    ],
    lbl: ['Email', 'Your name', 'Your Age Range', 'Your Gender', 'Race/Ethnicity', 'Employer Name', 'State of Employer',
        'Your Title/Position', 'Length of Employment', 'Salary Range'
    ]
};
//fields for db input - confirmed.js not sure why getter methods are not working for these.
var allFieldsMap = ['email', nonReqField[0], rngField[0], rngField[1], nonReqField[1], reqField[0], reqField[1],
    reqField[2], rngField[2], rngField[3]
];

var allFieldsType = ['String', 'String', 'Number', 'Number', 'String', 'String', 'String', 'String', 'Number', 'Number'];

//get methods for select box parameters, except states - dosurvey.handlebars
exports.getAgeRange = function() {
    return ageRange;
};
exports.getTheAgeRange = function(num) {
    return ageRange[num];
};
exports.getEmpSalary = function() {
    return empSalary;
};
exports.getSalaryValue = function(position){
    return empSalary[position];
};
exports.getGender = function() {
    return gender;
};
exports.getEmpDuration = function() {
    return empDuration;
};
exports.getEthnicity = function() {
    return ethnicity;
};

// get methods for inpForm data
exports.getReqFieldLen = function() {
    return reqField.length;
};
exports.getReqField = function(num) {
    return reqField[num];
};
exports.getNonReqFieldLen = function() {
    return nonReqField.length;
};
exports.getNonReqField = function(num) {
    return nonReqField[num];
};

// getter method for form results display - shosurvey.handlebars
exports.getResDisp = function(inpObj) {
    for (var i = 0; i < rngField.length; i++) { // takes each field that has a range and interprets that range
        inpObj[rngField[i]] = rngObj[i][inpObj[rngField[i]]];
    }
    var disp = {};
    for (var i = 0; i < resDisp.map.length; i++) {
        disp[resDisp.lbl[i]] = inpObj[resDisp.map[i]];
    }
    return disp;
};

exports.getLocation = function(userInp){
    var obj = {};
    obj[resDisp.lbl[7]] = userInp[resDisp.map[7]];
    return obj;
};

//get methods for allFields variable for db input - confirmed.js they are not working though. check later
exports.getAllFieldsLen = function() {
    return allFieldsMap.length;
};
exports.getAllFieldsMap = function(num) {
    return allFieldsMap[num];
};
exports.getAllFieldsType = function(num) {
    return allFieldsType[num];
};

// Dictionary!!!! States for select box - dosurvey.handlebars
var empState = {
    AL: 'Alabama',
    AK: 'Alaska',
    AZ: 'Arizona',
    AR: 'Arkansas',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DE: 'Delaware',
    DC: 'District of Columbia',
    FL: 'Florida',
    GA: 'Georgia',
    GU: 'Guam',
    HI: 'Hawaii',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    IA: 'Iowa',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    ME: 'Maine',
    MD: 'Maryland',
    MA: 'Massachusetts',
    MI: 'Michigan',
    MN: 'Minnesota',
    MS: 'Mississippi',
    MO: 'Missouri',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NY: 'New York',
    NC: 'North Carolina',
    ND: 'North Dakota',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PA: 'Pennsylvania',
    PR: 'Puerto Rico',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VI: 'Virgin Islands',
    VA: 'Virginia',
    WA: 'Washington',
    WV: 'West Virginia',
    WI: 'Wisconsin',
    WY: 'Wyoming'
};

var stateCode = {
    AL:'01',
    AK:'02',
    AZ:'04',
    AR:'05',
    CA:'06',
    CO:'08',
    CT:'09',
    DE:'10',
    DC:'11',
    FL:'12',
    GA:'13',
    HI:'15',
    ID:'16',
    IL:'17',
    IN:'18',
    IA:'19',
    KS:'20',
    KY:'21',
    LA:'22',
    ME:'23',
    MD:'24',
    MA:'25',
    MI:'26',
    MN:'27',
    MS:'28',
    MO:'29',
    MT:'30',
    NE:'31',
    NV:'32',
    NH:'33',
    NJ:'34',
    NM:'35',
    NY:'36',
    NC:'37',
    ND:'38',
    OH:'39',
    OK:'40',
    OR:'41',
    PA:'42',
    RI:'44',
    SC:'45',
    SD:'46',
    TN:'47',
    TX:'48',
    UT:'49',
    VT:'50',
    VA:'51',
    WA:'53',
    WV:'54',
    WI:'55',
    WY:'56',
    GU:'66',
    PR:'72',
    VI:'78'
};

var metropolitanAreas = {
    01: ['0011500','0012220','0013820','0019300', '0019460','0020020','0022520','0023460','0026620','0033660','0033860','0046220','0100001','0100002','0100003','0100004'],
    02: ['0011260', '0021820', '0200001','0200002'],
    04: ['0022380', '0029420', '0038060', '0039140', '0043420', '0046060', '0049740', '0400001'],
    05: ['0022220', '0022900', '0026300', '0027860', '0030780', '0038220', '0500001', '0500002', '0500003', '0500004'],
    06: ['0011244', '0012540', '0017020', '0020940', '0023420', '0025260', '0031080', '0031084', '0031460', '0032900', '0033700', '0034900', '0036084', '0037100', '0039820', '0040140', '0040900', '0041500', '0041740', '0041860', '0041884', '0041940', '0042020', '0042034', '0042100', '0042200', '0042220', '0044700', '0046700', '0047300', '0049700', '0600001', '0600002', '0600003', '0600004', '0600005'],
    08: ['00114500', '0017820', '0019740', '0022660', '0024300', '0024540', '0039380', '0800001', '0800002', '0800003'],
    09: ['0071950', '0072850', '0073450', '0075700', '0076450', '0078700', '0900001'],
    10: ['0020100', '0048864'],
    11: ['0047894', '0047900'],
    12: ['0015980', '0018880', '0019660', '0022744', '0023540', '0026140', '0027260', '0029460', '0033100', '0033124', '0034940', '0035840', '0036100', '0036740', '0037340', '0037460', '0037860', '0038940', '0039460', '0042680', '0042700', '0045220', '0045300', '0045540', '0048424', '1200001', '1200002', '1200003'],
    13: ['0010500', '0012020', '0012060', '0012260', '0015260', '0017980', '0019140', '0023580', '0025980', '0031420', '0040660', '0042340', '0046660', '0047580', '1300002', '1300003', '1300004'],
    15: ['0027980', '0046520', '1500001'],
    16: ['0014260', '0017660', '0026820', '0030300', '0038540', '1600001', '1600002', '1600003', '1600004'],
    17: ['0014010', '0016060', '0016580', '0016974', '0016980', '0019180', '0019500', '0020994', '0028100', '0029404', '0037900', '0040420', '0044100', '1700001', '1700002', '1700003', '1700004'],
    18: ['0014020', '0018020', '0021140', '0021780', '0023060', '0023844', '0026900', '0029020', '0029200', '0033140', '0034620', '0043780', '0045460', '1800001', '1800002', '1800003'],
    19: ['0011180', '0016300', '0019340', '0019780', '0020220', '0026980', '0043580', '0049740', '1900001', '1900002', '1900003', '1900004'],
    20: ['0029940', '0031740', '0045820', '0048620', '2000001', '2000002', '2000003', '2000004'],
    21: ['0014540', '0021060', '0030460', '0031140', '0036980', '2100001', '2100002', '2100003', '2100004'],
    22: ['0010780', '0012940', '0025220', '0026380', '0029180', '0029340', '0033740', '0035380', '0043340', '2200001', '2200002', '2200003', '2200004'],
    23: ['0070750', '0074650', '0076700', '2300001', '2300002'],
    24: ['0012580', '0015680', '0019060', '0025180', '0041540', '0043524', '2400001', '2400002'],
    25: ['0070900', '0071650', '0071654', '0072104', '0073104', '0073504', '0074204', '0074500', '0074804', '0074854', '0075550', '0076524', '0076600', '0078100', '0078254', '0079600', '2500001', '2500002', '2500003', '2500004'],
    26: ['0011460', '0012980', '0013020', '0019804', '0019820', '0022420', '0024340', '0027100', '0028020', '0029620', '0033220', '0033780', '0034740', '0035660', '0040980', '0047664', '2600001', '2600002', '2600003', '2600004'],
    27: ['0020260', '0031860', '0033460', '0040340', '0041060', '2700001', '2700002', '2700003', '2700004'],
    28: ['0025060', '0025620', '0027140', '2800001', '2800002', '2800003', '2800004'],
    29: ['0016020', '0017860', '0027620', '0027900', '0028140', '0041140', '0041180', '0044180', '2900001', '2900002', '2900003', '2900004'],
    30: ['0013740', '0024500', '0033540', '3000001', '3000002', '3000003', '3000004'],
    31: ['0024260', '0030700', '0036540', '3100001', '3100002', '3100003', '3100004'],
    32: ['0016180', '0029820', '0039900', '3200001', '3200002'],
    33: ['0073050', '0074950', '0075404', '0076900', '3300001', '3300002', '3300003', '3300004'],
    34: ['0012100', '0015804', '0035084', '0036140', '0045940', '0047220'],
    35: ['0010740', '0022140', '0029740', '0042140', '3500001', '3500002', '3500003', '3500004'],
    36: ['0010580', '0013780', '0015380', '0020524', '0021300', '0024020', '0027060', '0028740', '0035004', '0035614', '0035620', '0040380', '0045060', '0046540', '0048060', '3600001', '3600002', '3600003', '3600004'],
    37: ['0011700', '0015500', '0016740', '0020500', '0022180', '0024140', '0024660', '0024780', '0025860', '0027340', '0035100', '0039580', '0040580', '0048900', '0049180', '3700001', '3700002', '3700003', '3700004'],
    38: ['0013900', '0022020', '0024220', '3800001', '3800002', '3800003', '3800004'],
    39: ['0010420', '0015940', '0017140', '0017460', '0018140', '0019380', '0030620', '0031900', '0044220', '0045780', '0049660', '3900001', '3900002', '3900003', '3900004'],
    40: ['0030020', '0036420', '0046140', '4000001', '4000002', '4000003', '4000004'],
    41: ['0010540', '0013460', '0018700', '0021660', '0024420', '0032780', '0038900', '0041420', '4100001', '4100002', '4100003', '4100004'],
    42: ['0010900', '0011020', '0014100', '0016540', '0020700', '0021500', '0023900', '0025420', '0027780', '0029540', '0030140', '0033874', '0037964', '0037980', '0038300', '0039740', '0042540', '0044300', '0048700', '0049620', '4200001', '4200002', '4200003'],
    44: ['0077200', '4400001'],
    45: ['0016700', '0017900', '0022500', '0024860', '0025940', '0034820', '0043900', '0044940', '4500001', '4500002', '4500003', '4500004'],
    46: ['0039660', '0043620', '4600002', '4600003'],
    47: ['0016860', '0017300', '0017420', '0027180', '0027740', '0028700', '0028940', '0032820', '0034100', '0034980', '4700001', '4700002', '4700003', '4700004'],
    48: ['0010180', '0011100', '0012420', '0013140', '0015180', '0017780', '0018580', '0019100', '0019124', '0021340', '0023104', '0026420', '0028660', '0029700', '0030980', '0031180', '0032580', '0033260', '0036220', '0041660', '0041700', '0043300', '0045500', '0046340', '0047020', '0047380', '0048660', '4800001', '4800002', '4800003', '4800004'],
    49: ['0030860', '0036260', '0039340', '0041100', '0041620', '4900001', '4900002', '4900003', '4900004'],
    50: ['5000001', '5000002'],
    51: ['0013980', '0016820', '0025500', '0031340', '0040060', '0040220', '00444420', '0047260', '0049020', '5100001', '5100002', '5100003', '5100004'],
    53: ['0013380', '0014740', '0028420', '0031020', '0034580', '0036500', '0042644', '0042660', '0044060', '0045104', '0047460', '0048300', '0049420', '5300001', '5300002', '5300003', '5300004'],
    54: ['0013220', '0016620', '0026580', '0034060', '0037620', '0048260', '0048540', '5400001', '5400002'],
    55: ['0011540', '0020740', '0022540', '0024580', '0027500', '0029100', '0031540', '0033340', '0036780', '0039540', '0043100', '0048140', '5500001', '5500002', '5500003', '5500004'],
    56: ['0016220', '0016940', '5600001', '5600002', '5600003', '5600004'],
    66: ['6600000'],
    72: ['0010380', '0011640', '0025020', '0032420', '0038660', '0041900', '0041980', '7200001', '7200002'],
    78: ['7800000']

};

exports.getStateCode = function (stateAbb){
    return stateCode[stateAbb];
};


exports.getMetroArea = function(code){
    var metroAreas = {};
            console.log("this is the state code: " + code);

    if(metropolitanAreas.hasOwnProperty(code)){
        for(var i = 0; i < metropolitanAreas[code].length; i++){
            metroAreas[i] = metropolitanAreas[code][i];
            console.log("metrooAreas " + metroAreas[i]);
        }
    }
    return metroAreas;
};

exports.getEmpState = function() {
    return empState;
};

exports.matchStateByAbb = function(abb) {
    return empState[abb];
};

var occupationsList = [
    'Accountants and Auditors',
    'Actors',
    'Actors, Producers, and Directors',
    'Actuaries',
    'Adhesive Bonding Machine Operators and Tenders',
    'Administrative Law Judges, Adjudicators, and Hearing Officers',
    'Administrative Services Managers',
    'Adult Basic and Secondary Education and Literacy Teachers and Instructors',
    'Advertising and Promotions Managers',
    'Advertising Sales Agents',
    'Advertising, Marketing, Promotions, Public Relations, and Sales Managers',
    'Aerospace Engineering and Operations Technicians',
    'Aerospace Engineers',
    'Agents and Business Managers of Artists, Performers, and Athletes',
    'Agricultural and Food Science Technicians',
    'Agricultural and Food Scientists',
    'Agricultural Engineers',
    'Agricultural Equipment Operators',
    'Agricultural Inspectors',
    'Agricultural Sciences Teachers, Postsecondary',
    'Agricultural Workers',
    'Air Traffic Controllers',
    'Air Traffic Controllers and Airfield Operations Specialists',
    'Air Transportation Workers',
    'Aircraft Cargo Handling Supervisors',
    'Aircraft Mechanics and Service Technicians',
    'Aircraft Pilots and Flight Engineers',
    'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
    'Airfield Operations Specialists',
    'Airline Pilots, Copilots, and Flight Engineers',
    'Ambulance Drivers and Attendants, Except Emergency Medical Technicians',
    'Amusement and Recreation Attendants',
    'Anesthesiologists',
    'Animal Breeders',
    'Animal Care and Service Workers',
    'Animal Control Workers',
    'Animal Scientists',
    'Animal Trainers',
    'Announcers',
    'Anthropologists and Archeologists',
    'Anthropology and Archeology Teachers, Postsecondary',
    'Appraisers and Assessors of Real Estate',
    'Arbitrators, Mediators, and Conciliators',
    'Architects, Except Landscape and Naval',
    'Architects, Except Naval',
    'Architects, Surveyors, and Cartographers',
    'Architectural and Civil Drafters',
    'Architectural and Engineering Managers',
    'Architecture and Engineering Occupations',
    'Architecture Teachers, Postsecondary',
    'Archivists',
    'Archivists, Curators, and Museum Technicians',
    'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
    'Art and Design Workers',
    'Art Directors',
    'Art, Drama, and Music Teachers, Postsecondary',
    'Artists and Related Workers',
    'Arts, Communications, and Humanities Teachers, Postsecondary',
    'Arts, Design, Entertainment, Sports, and Media Occupations',
    'Assemblers and Fabricators',
    'Astronomers',
    'Astronomers and Physicists',
    'Athletes and Sports Competitors',
    'Athletes, Coaches, Umpires, and Related Workers',
    'Athletic Trainers',
    'Atmospheric and Space Scientists',
    'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary',
    'Audio and Video Equipment Technicians',
    'Audiologists',
    'Audio-Visual and Multimedia Collections Specialists',
    'Automotive and Watercraft Service Attendants',
    'Automotive Body and Related Repairers',
    'Automotive Glass Installers and Repairers',
    'Automotive Service Technicians and Mechanics',
    'Automotive Technicians and Repairers',
    'Avionics Technicians',
    'Baggage Porters and Bellhops',
    'Baggage Porters, Bellhops, and Concierges',
    'Bailiffs',
    'Bailiffs, Correctional Officers, and Jailers',
    'Bakers',
    'Barbers',
    'Barbers, Hairdressers, Hairstylists and Cosmetologists',
    'Bartenders',
    'Bicycle Repairers',
    'Bill and Account Collectors',
    'Billing and Posting Clerks',
    'Biochemists and Biophysicists',
    'Biological Science Teachers, Postsecondary',
    'Biological Scientists',
    'Biological Technicians',
    'Biomedical Engineers',
    'Boilermakers',
    'Bookkeeping, Accounting, and Auditing Clerks',
    'Brickmasons and Blockmasons',
    'Brickmasons, Blockmasons, and Stonemasons',
    'Bridge and Lock Tenders',
    'Broadcast and Sound Engineering Technicians and Radio Operators',
    'Broadcast News Analysts',
    'Broadcast Technicians',
    'Brokerage Clerks',
    'Budget Analysts',
    'Building and Grounds Cleaning and Maintenance Occupations',
    'Building Cleaning and Pest Control Workers',
    'Building Cleaning Workers',
    'Bus and Truck Mechanics and Diesel Engine Specialists',
    'Bus Drivers',
    'Bus Drivers, School or Special Client',
    'Bus Drivers, Transit and Intercity',
    'Business and Financial Operations Occupations',
    'Business Operations Specialists',
    'Business Teachers, Postsecondary',
    'Butchers and Meat Cutters',
    'Butchers and Other Meat, Poultry, and Fish Processing Workers',
    'Buyers and Purchasing Agents',
    'Buyers and Purchasing Agents, Farm Products',
    'Cabinetmakers and Bench Carpenters',
    'Camera and Photographic Equipment Repairers',
    'Camera Operators, Television, Video, and Motion Picture',
    'Captains, Mates, and Pilots of Water Vessels',
    'Cardiovascular Technologists and Technicians',
    'Career/Technical Education Teachers, Middle School',
    'Career/Technical Education Teachers, Secondary School',
    'Cargo and Freight Agents',
    'Carpenters',
    'Carpet Installers',
    'Carpet, Floor, and Tile Installers and Finishers',
    'Cartographers and Photogrammetrists',
    'Cashiers',
    'Cashiers',
    'Cement Masons and Concrete Finishers',
    'Cement Masons, Concrete Finishers, and Terrazzo Workers',
    'Chefs and Head Cooks',
    'Chemical Engineers',
    'Chemical Equipment Operators and Tenders',
    'Chemical Plant and System Operators',
    'Chemical Processing Machine Setters, Operators, and Tenders',
    'Chemical Technicians',
    'Chemistry Teachers, Postsecondary',
    'Chemists',
    'Chemists and Materials Scientists',
    'Chief Executives',
    'Child, Family, and School Social Workers',
    'Childcare Workers',
    'Chiropractors',
    'Choreographers',
    'Civil Engineering Technicians',
    'Civil Engineers',
    'Claims Adjusters, Appraisers, Examiners, and Investigators',
    'Claims Adjusters, Examiners, and Investigators',
    'Cleaners of Vehicles and Equipment',
    'Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders',
    'Clergy',
    'Clinical Laboratory Technologists and Technicians',
    'Clinical, Counseling, and School Psychologists',
    'Coaches and Scouts',
    'Coating, Painting, and Spraying Machine Setters, Operators, and Tenders',
    'Coil Winders, Tapers, and Finishers',
    'Coin, Vending, and Amusement Machine Servicers and Repairers',
    'Combined Food Preparation and Serving Workers, Including Fast Food',
    'Commercial and Industrial Designers',
    'Commercial Divers',
    'Commercial Pilots',
    'Communications Equipment Operators',
    'Communications Teachers, Postsecondary',
    'Community and Social Service Occupations',
    'Community Health Workers',
    'Compensation and Benefits Managers',
    'Compensation, Benefits, and Job Analysis Specialists',
    'Compliance Officers',
    'Computer and Information Analysts',
    'Computer and Information Research Scientists',
    'Computer and Information Systems Managers',
    'Computer and Mathematical Occupations',
    'Computer Control Programmers and Operators',
    'Computer Hardware Engineers',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic',
    'Computer Occupations',
    'Computer Operators',
    'Computer Programmers',
    'Computer Science Teachers, Postsecondary',
    'Computer Support Specialists',
    'Computer Systems Analysts',
    'Computer User Support Specialists',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Computer-Controlled Machine Tool Operators, Metal and Plastic',
    'Concierges',
    'Conservation Scientists',
    'Conservation Scientists and Foresters',
    'Construction and Building Inspectors',
    'Construction and Extraction Occupations',
    'Construction Equipment Operators',
    'Construction Laborers',
    'Construction Managers',
    'Construction Trades Workers',
    'Continuous Mining Machine Operators',
    'Control and Valve Installers and Repairers',
    'Control and Valve Installers and Repairers, Except Mechanical Door',
    'Conveyor Operators and Tenders',
    'Cooks',
    'Cooks and Food Preparation Workers',
    'Cooks, Fast Food',
    'Cooks, Institution and Cafeteria',
    'Cooks, Private Household',
    'Cooks, Restaurant',
    'Cooks, Short Order',
    'Cooling and Freezing Equipment Operators and Tenders',
    'Correctional Officers and Jailers',
    'Correspondence Clerks',
    'Cost Estimators',
    'Costume Attendants',
    'Counselors',
    'Counselors, Social Workers, and Other Community and Social Service Specialists',
    'Counter and Rental Clerks',
    'Counter and Rental Clerks and Parts Salespersons',
    'Counter Attendants, Cafeteria, Food Concession, and Coffee Shop',
    'Couriers and Messengers',
    'Court Reporters',
    'Court, Municipal, and License Clerks',
    'Craft Artists',
    'Crane and Tower Operators',
    'Credit Analysts',
    'Credit Authorizers, Checkers, and Clerks',
    'Credit Counselors',
    'Credit Counselors and Loan Officers',
    'Criminal Justice and Law Enforcement Teachers, Postsecondary',
    'Crossing Guards',
    'Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders',
    'Crushing, Grinding, Polishing, Mixing, and Blending Workers',
    'Curators',
    'Customer Service Representatives',
    'Cutters and Trimmers, Hand',
    'Cutting and Slicing Machine Setters, Operators, and Tenders',
    'Cutting Workers',
    'Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Dancers',
    'Dancers and Choreographers',
    'Data Entry and Information Processing Workers',
    'Data Entry Keyers',
    'Database Administrators',
    'Database and Systems Administrators and Network Architects',
    'Demonstrators and Product Promoters',
    'Dental Assistants',
    'Dental Hygienists',
    'Dental Laboratory Technicians',
    'Dentists',
    'Dentists, General',
    'Derrick Operators, Oil and Gas',
    'Derrick, Rotary Drill, and Service Unit Operators, Oil, Gas, and Mining',
    'Designers',
    'Desktop Publishers',
    'Detectives and Criminal Investigators',
    'Diagnostic Medical Sonographers',
    'Diagnostic Related Technologists and Technicians',
    'Dietetic Technicians',
    'Dietitians and Nutritionists',
    'Dining Room and Cafeteria Attendants and Bartender Helpers',
    'Directors, Religious Activities and Education',
    'Dishwashers',
    'Dispatchers',
    'Dispatchers, Except Police, Fire, and Ambulance',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Drafters',
    'Drafters, Engineering Technicians, and Mapping Technicians',
    'Dredge Operators',
    'Dredge, Excavating, and Loading Machine Operators',
    'Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Driver/Sales Workers',
    'Driver/Sales Workers and Truck Drivers',
    'Drywall and Ceiling Tile Installers',
    'Drywall Installers, Ceiling Tile Installers, and Tapers',
    'Earth Drillers, Except Oil and Gas',
    'Economics Teachers, Postsecondary',
    'Economists',
    'Editors',
    'Education Administrators',
    'Education Administrators, Elementary and Secondary School',
    'Education Administrators, Postsecondary',
    'Education Administrators, Preschool and Childcare Center/Program',
    'Education and Library Science Teachers, Postsecondary',
    'Education Teachers, Postsecondary',
    'Education, Training, and Library Occupations',
    'Educational, Guidance, School, and Vocational Counselors',
    'Electric Motor, Power Tool, and Related Repairers',
    'Electrical and Electronic Equipment Assemblers',
    'Electrical and Electronic Equipment Mechanics, Installers, and Repairers',
    'Electrical and Electronics Drafters',
    'Electrical and Electronics Engineering Technicians',
    'Electrical and Electronics Engineers',
    'Electrical and Electronics Installers and Repairers, Transportation Equipment',
    'Electrical and Electronics Repairers, Commercial and Industrial Equipment',
    'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
    'Electrical Engineers',
    'Electrical Power-Line Installers and Repairers',
    'Electrical, Electronics, and Electromechanical Assemblers',
    'Electricians',
    'Electromechanical Equipment Assemblers',
    'Electro-Mechanical Technicians',
    'Electronic Equipment Installers and Repairers, Motor Vehicles',
    'Electronic Home Entertainment Equipment Installers and Repairers',
    'Electronics Engineers, Except Computer',
    'Elementary and Middle School Teachers',
    'Elementary School Teachers, Except Special Education',
    'Elevator Installers and Repairers',
    'Eligibility Interviewers, Government Programs',
    'Embalmers',
    'Emergency Management Directors',
    'Emergency Medical Technicians and Paramedics',
    'Engine and Other Machine Assemblers',
    'Engineering and Architecture Teachers, Postsecondary',
    'Engineering Teachers, Postsecondary',
    'Engineering Technicians, Except Drafters',
    'Engineers',
    'English Language and Literature Teachers, Postsecondary',
    'Entertainers and Performers, Sports and Related Workers',
    'Entertainment Attendants and Related Workers',
    'Environmental Engineering Technicians',
    'Environmental Engineers',
    'Environmental Science and Protection Technicians, Including Health',
    'Environmental Science Teachers, Postsecondary',
    'Environmental Scientists and Geoscientists',
    'Environmental Scientists and Specialists, Including Health',
    'Epidemiologists',
    'Etchers and Engravers',
    'Excavating and Loading Machine and Dragline Operators',
    'Executive Secretaries and Executive Administrative Assistants',
    'Exercise Physiologists',
    'Explosives Workers, Ordnance Handling Experts, and Blasters',
    'Extraction Workers',
    'Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers',
    'Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders',
    'Fabric and Apparel Patternmakers',
    'Fabric Menders, Except Garment',
    'Fallers',
    'Family and General Practitioners',
    'Farm and Home Management Advisors',
    'Farm Equipment Mechanics and Service Technicians',
    'Farm Labor Contractors',
    'Farmers, Ranchers, and Other Agricultural Managers',
    'Farming, Fishing, and Forestry Occupations',
    'Farmworkers and Laborers, Crop, Nursery, and Greenhouse',
    'Farmworkers, Farm, Ranch, and Aquacultural Animals',
    'Fashion Designers',
    'Fast Food and Counter Workers',
    'Fence Erectors',
    'Fiberglass Laminators and Fabricators',
    'File Clerks',
    'Film and Video Editors',
    'Financial Analysts',
    'Financial Analysts and Advisors',
    'Financial Clerks',
    'Financial Examiners',
    'Financial Managers',
    'Financial Specialists',
    'Fine Artists, Including Painters, Sculptors, and Illustrators',
    'Fire Fighting and Prevention Workers',
    'Fire Inspectors',
    'Fire Inspectors and Investigators',
    'Firefighters',
    'First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers',
    'First-Line Supervisors of Construction Trades and Extraction Workers',
    'First-Line Supervisors of Correctional Officers',
    'First-Line Supervisors of Farming, Fishing, and Forestry Workers',
    'First-Line Supervisors of Fire Fighting and Prevention Workers',
    'First-Line Supervisors of Food Preparation and Serving Workers',
    'First-Line Supervisors of Gaming Workers',
    'First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand',
    'First-Line Supervisors of Housekeeping and Janitorial Workers',
    'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers',
    'First-Line Supervisors of Law Enforcement Workers',
    'First-Line Supervisors of Mechanics, Installers, and Repairers',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Office and Administrative Support Workers',
    'First-Line Supervisors of Personal Service Workers',
    'First-Line Supervisors of Police and Detectives',
    'First-Line Supervisors of Production and Operating Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'First-Line Supervisors of Sales Workers',
    'First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators',
    'Fish and Game Wardens',
    'Fishers and Related Fishing Workers',
    'Fishing and Hunting Workers',
    'Fitness Trainers and Aerobics Instructors',
    'Flight Attendants',
    'Floor Layers, Except Carpet, Wood, and Hard Tiles',
    'Floor Sanders and Finishers',
    'Floral Designers',
    'Food and Beverage Serving Workers',
    'Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders',
    'Food Batchmakers',
    'Food Cooking Machine Operators and Tenders',
    'Food Preparation and Serving Related Occupations',
    'Food Preparation Workers',
    'Food Processing Workers',
    'Food Scientists and Technologists',
    'Food Servers, Nonrestaurant',
    'Food Service Managers',
    'Foreign Language and Literature Teachers, Postsecondary',
    'Forensic Science Technicians',
    'Forest and Conservation Technicians',
    'Forest and Conservation Workers',
    'Forest Fire Inspectors and Prevention Specialists',
    'Forest, Conservation, and Logging Workers',
    'Foresters',
    'Forestry and Conservation Science Teachers, Postsecondary',
    'Forging Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Forming Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Foundry Mold and Coremakers',
    'Fundraisers',
    'Funeral Attendants',
    'Funeral Service Managers',
    'Funeral Service Workers',
    'Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders',
    'Furniture Finishers',
    'Gaming and Sports Book Writers and Runners',
    'Gaming Cage Workers',
    'Gaming Change Persons and Booth Cashiers',
    'Gaming Dealers',
    'Gaming Managers',
    'Gaming Services Workers',
    'Gaming Supervisors',
    'Gaming Surveillance Officers and Gaming Investigators',
    'Gas Compressor and Gas Pumping Station Operators',
    'Gas Plant Operators',
    'General and Operations Managers',
    'Genetic Counselors',
    'Geographers',
    'Geography Teachers, Postsecondary',
    'Geological and Petroleum Technicians',
    'Geoscientists, Except Hydrologists and Geographers',
    'Glaziers',
    'Graders and Sorters, Agricultural Products',
    'Graduate Teaching Assistants',
    'Graphic Designers',
    'Grinding and Polishing Workers, Hand',
    'Grinding/Lapping/Polishing/Buffing Machine Tool Setters, Operators, and Tenders, Metal and Pla',
    'Grounds Maintenance Workers',
    'Hairdressers, Hairstylists, and Cosmetologists',
    'Hazardous Materials Removal Workers',
    'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
    'Health Diagnosing and Treating Practitioners',
    'Health Educators',
    'Health Practitioner Support Technologists and Technicians',
    'Health Specialties Teachers, Postsecondary',
    'Health Teachers, Postsecondary',
    'Health Technologists and Technicians',
    'Healthcare Practitioners and Technical Occupations',
    'Healthcare Social Workers',
    'Healthcare Support Occupations',
    'Hearing Aid Specialists',
    'Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic',
    'Heating, Air Conditioning, and Refrigeration Mechanics and Installers',
    'Heavy and Tractor-Trailer Truck Drivers',
    'Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics',
    'Helpers, Construction Trades',
    'Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters',
    'Helpers--Carpenters',
    'Helpers--Electricians',
    'Helpers--Extraction Workers',
    'Helpers--Installation, Maintenance, and Repair Workers',
    'Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons',
    'Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters',
    'Helpers--Production Workers',
    'Helpers--Roofers',
    'Highway Maintenance Workers',
    'Historians',
    'History Teachers, Postsecondary',
    'Hoist and Winch Operators',
    'Home Appliance Repairers',
    'Home Economics Teachers, Postsecondary',
    'Home Health Aides',
    'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop',
    'Hotel, Motel, and Resort Desk Clerks',
    'Human Resources Assistants, Except Payroll and Timekeeping',
    'Human Resources Managers',
    'Human Resources Specialists',
    'Human Resources Workers',
    'Hydrologists',
    'Industrial Engineering Technicians',
    'Industrial Engineers',
    'Industrial Engineers, Including Health and Safety',
    'Industrial Machinery Installation, Repair, and Maintenance Workers',
    'Industrial Machinery Mechanics',
    'Industrial Production Managers',
    'Industrial Truck and Tractor Operators',
    'Industrial-Organizational Psychologists',
    'Information and Record Clerks',
    'Information Security Analysts',
    'Inspectors, Testers, Sorters, Samplers, and Weighers',
    'Installation, Maintenance, and Repair Occupations',
    'Instructional Coordinators',
    'Insulation Workers',
    'Insulation Workers, Floor, Ceiling, and Wall',
    'Insulation Workers, Mechanical',
    'Insurance Appraisers, Auto Damage',
    'Insurance Claims and Policy Processing Clerks',
    'Insurance Sales Agents',
    'Insurance Underwriters',
    'Interior Designers',
    'Internists, General',
    'Interpreters and Translators',
    'Interviewers, Except Eligibility and Loan',
    'Janitors and Cleaners, Except Maids and Housekeeping Cleaners',
    'Jewelers and Precious Stone and Metal Workers',
    'Judges, Magistrate Judges, and Magistrates',
    'Judges, Magistrates, and Other Judicial Workers',
    'Judicial Law Clerks',
    'Kindergarten Teachers, Except Special Education',
    'Labor Relations Specialists',
    'Laborers and Freight, Stock, and Material Movers, Hand',
    'Laborers and Material Movers, Hand',
    'Landscape Architects',
    'Landscaping and Groundskeeping Workers',
    'Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Laundry and Dry-Cleaning Workers',
    'Law Enforcement Workers',
    'Law Teachers, Postsecondary',
    'Law, Criminal Justice, and Social Work Teachers, Postsecondary',
    'Lawyers',
    'Lawyers and Judicial Law Clerks',
    'Lawyers, Judges, and Related Workers',
    'Layout Workers, Metal and Plastic',
    'Legal Occupations',
    'Legal Secretaries',
    'Legal Support Workers',
    'Legislators',
    'Librarians',
    'Librarians, Curators, and Archivists',
    'Library Assistants, Clerical',
    'Library Science Teachers, Postsecondary',
    'Library Technicians',
    'Licensed Practical and Licensed Vocational Nurses',
    'Life Sciences Teachers, Postsecondary',
    'Life Scientists',
    'Life, Physical, and Social Science Occupations',
    'Life, Physical, and Social Science Technicians',
    'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers',
    'Light Truck or Delivery Services Drivers',
    'Line Installers and Repairers',
    'Loading Machine Operators, Underground Mining',
    'Loan Interviewers and Clerks',
    'Loan Officers',
    'Locker Room, Coatroom, and Dressing Room Attendants',
    'Locksmiths and Safe Repairers',
    'Locomotive Engineers',
    'Locomotive Engineers and Operators',
    'Locomotive Firers',
    'Lodging Managers',
    'Log Graders and Scalers',
    'Logging Equipment Operators',
    'Logging Workers',
    'Logisticians',
    'Machine Feeders and Offbearers',
    'Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic',
    'Machinists',
    'Magnetic Resonance Imaging Technologists',
    'Maids and Housekeeping Cleaners',
    'Mail Clerks and Mail Machine Operators, Except Postal Service',
    'Maintenance and Repair Workers, General',
    'Maintenance Workers, Machinery',
    'Makeup Artists, Theatrical and Performance',
    'Management Analysts',
    'Management Occupations',
    'Manicurists and Pedicurists',
    'Manufactured Building and Mobile Home Installers',
    'Marine Engineers and Naval Architects',
    'Market Research Analysts and Marketing Specialists',
    'Marketing and Sales Managers',
    'Marketing Managers',
    'Marriage and Family Therapists',
    'Massage Therapists',
    'Material Moving Workers',
    'Material Recording, Scheduling, Dispatching, and Distributing Workers',
    'Materials Engineers',
    'Materials Scientists',
    'Math and Computer Teachers, Postsecondary',
    'Mathematical Science Occupations',
    'Mathematical Science Teachers, Postsecondary',
    'Mathematical Technicians',
    'Mathematicians',
    'Meat, Poultry, and Fish Cutters and Trimmers',
    'Mechanical Door Repairers',
    'Mechanical Drafters',
    'Mechanical Engineering Technicians',
    'Mechanical Engineers',
    'Media and Communication Equipment Workers',
    'Media and Communication Workers',
    'Medical and Clinical Laboratory Technicians',
    'Medical and Clinical Laboratory Technologists',
    'Medical and Health Services Managers',
    'Medical Appliance Technicians',
    'Medical Assistants',
    'Medical Equipment Preparers',
    'Medical Equipment Repairers',
    'Medical Records and Health Information Technicians',
    'Medical Scientists',
    'Medical Scientists, Except Epidemiologists',
    'Medical Secretaries',
    'Medical Transcriptionists',
    'Medical, Dental, and Ophthalmic Laboratory Technicians',
    'Meeting, Convention, and Event Planners',
    'Mental Health and Substance Abuse Social Workers',
    'Mental Health Counselors',
    'Merchandise Displayers and Window Trimmers',
    'Metal Furnace Operators, Tenders, Pourers, and Casters',
    'Metal Workers and Plastic Workers',
    'Metal-Refining Furnace Operators and Tenders',
    'Meter Readers, Utilities',
    'Microbiologists',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Millwrights',
    'Mine Cutting and Channeling Machine Operators',
    'Mine Shuttle Car Operators',
    'Mining and Geological Engineers, Including Mining Safety Engineers',
    'Mining Machine Operators',
    'Miscellaneous Agricultural Workers',
    'Miscellaneous Assemblers and Fabricators',
    'Miscellaneous Community and Social Service Specialists',
    'Miscellaneous Construction and Related Workers',
    'Miscellaneous Electrical and Electronic Equipment Mechanics, Installers, and Repairers',
    'Miscellaneous Entertainment Attendants and Related Workers',
    'Miscellaneous Food Processing Workers',
    'Miscellaneous Health Practitioners and Technical Workers',
    'Miscellaneous Health Technologists and Technicians',
    'Miscellaneous Healthcare Support Occupations',
    'Miscellaneous Installation, Maintenance, and Repair Workers',
    'Miscellaneous Legal Support Workers',
    'Miscellaneous Life, Physical, and Social Science Technicians',
    'Miscellaneous Mathematical Science Occupations',
    'Miscellaneous Media and Communication Workers',
    'Miscellaneous Metal Workers and Plastic Workers',
    'Miscellaneous Personal Appearance Workers',
    'Miscellaneous Plant and System Operators',
    'Miscellaneous Postsecondary Teachers',
    'Miscellaneous Production Workers',
    'Miscellaneous Protective Service Workers',
    'Miscellaneous Sales and Related Workers',
    'Miscellaneous Social Scientists and Related Workers',
    'Miscellaneous Teachers and Instructors',
    'Miscellaneous Textile, Apparel, and Furnishings Workers',
    'Miscellaneous Vehicle and Mobile Equipment Mechanics, Installers, and Repairers',
    'Mixing and Blending Machine Setters, Operators, and Tenders',
    'Mobile Heavy Equipment Mechanics, Except Engines',
    'Model Makers and Patternmakers, Metal and Plastic',
    'Model Makers and Patternmakers, Wood',
    'Model Makers, Metal and Plastic',
    'Model Makers, Wood',
    'Models',
    'Models, Demonstrators, and Product Promoters',
    'Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Molders, Shapers, and Casters, Except Metal and Plastic',
    'Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Morticians, Undertakers, and Funeral Directors',
    'Motion Picture Projectionists',
    'Motor Vehicle Operators',
    'Motorboat Mechanics and Service Technicians',
    'Motorboat Operators',
    'Motorcycle Mechanics',
    'Multimedia Artists and Animators',
    'Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Museum Technicians and Conservators',
    'Music Directors and Composers',
    'Musical Instrument Repairers and Tuners',
    'Musicians and Singers',
    'Musicians, Singers, and Related Workers',
    'Natural Sciences Managers',
    'Network and Computer Systems Administrators',
    'New Accounts Clerks',
    'News Analysts, Reporters and Correspondents',
    'Nonfarm Animal Caretakers',
    'Nuclear Engineers',
    'Nuclear Medicine Technologists',
    'Nuclear Power Reactor Operators',
    'Nuclear Technicians',
    'Nurse Anesthetists',
    'Nurse Midwives',
    'Nurse Practitioners',
    'Nursing Assistants',
    'Nursing Instructors and Teachers, Postsecondary',
    'Nursing, Psychiatric, and Home Health Aides',
    'Obstetricians and Gynecologists',
    'Occupational Health and Safety Specialists',
    'Occupational Health and Safety Specialists and Technicians',
    'Occupational Health and Safety Technicians',
    'Occupational Therapists',
    'Occupational Therapy Aides',
    'Occupational Therapy and Physical Therapist Assistants and Aides',
    'Occupational Therapy Assistants',
    'Occupational Therapy Assistants and Aides',
    'Office and Administrative Support Occupations',
    'Office Clerks, General',
    'Office Machine Operators, Except Computer',
    'Operating Engineers and Other Construction Equipment Operators',
    'Operations Research Analysts',
    'Operations Specialties Managers',
    'Ophthalmic Laboratory Technicians',
    'Ophthalmic Medical Technicians',
    'Opticians, Dispensing',
    'Optometrists',
    'Oral and Maxillofacial Surgeons',
    'Order Clerks',
    'Orderlies',
    'Orthodontists',
    'Orthotists and Prosthetists',
    'Other Construction and Related Workers',
    'Other Education, Training, and Library Occupations',
    'Other Food Preparation and Serving Related Workers',
    'Other Healthcare Practitioners and Technical Occupations',
    'Other Healthcare Support Occupations',
    'Other Installation, Maintenance, and Repair Occupations',
    'Other Management Occupations',
    'Other Office and Administrative Support Workers',
    'Other Personal Care and Service Workers',
    'Other Production Occupations',
    'Other Protective Service Workers',
    'Other Sales and Related Workers',
    'Other Teachers and Instructors',
    'Other Transportation Workers',
    'Outdoor Power Equipment and Other Small Engine Mechanics',
    'Packaging and Filling Machine Operators and Tenders',
    'Packers and Packagers, Hand',
    'Painters and Paperhangers',
    'Painters, Construction and Maintenance',
    'Painters, Transportation Equipment',
    'Painting Workers',
    'Painting, Coating, and Decorating Workers',
    'Paper Goods Machine Setters, Operators, and Tenders',
    'Paperhangers',
    'Paralegals and Legal Assistants',
    'Parking Enforcement Workers',
    'Parking Lot Attendants',
    'Parts Salespersons',
    'Patternmakers, Metal and Plastic',
    'Patternmakers, Wood',
    'Paving, Surfacing, and Tamping Equipment Operators',
    'Payroll and Timekeeping Clerks',
    'Pediatricians, General',
    'Personal Appearance Workers',
    'Personal Care Aides',
    'Personal Care and Service Occupations',
    'Personal Financial Advisors',
    'Pest Control Workers',
    'Pesticide Handlers, Sprayers, and Applicators, Vegetation',
    'Petroleum Engineers',
    'Petroleum Pump System Operators, Refinery Operators, and Gaugers',
    'Pharmacists',
    'Pharmacy Aides',
    'Pharmacy Technicians',
    'Philosophy and Religion Teachers, Postsecondary',
    'Phlebotomists',
    'Photographers',
    'Photographic Process Workers and Processing Machine Operators',
    'Physical Sciences Teachers, Postsecondary',
    'Physical Scientists',
    'Physical Therapist Aides',
    'Physical Therapist Assistants',
    'Physical Therapist Assistants and Aides',
    'Physical Therapists',
    'Physician Assistants',
    'Physicians and Surgeons',
    'Physicists',
    'Physics Teachers, Postsecondary',
    'Pile-Driver Operators',
    'Pipelayers',
    'Pipelayers, Plumbers, Pipefitters, and Steamfitters',
    'Plant and System Operators',
    'Plasterers and Stucco Masons',
    'Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Plumbers, Pipefitters, and Steamfitters',
    'Podiatrists',
    'Police and Sheriff\'s Patrol Officers',
    'Police Officers',
    'Police, Fire, and Ambulance Dispatchers',
    'Political Science Teachers, Postsecondary',
    'Political Scientists',
    'Postal Service Clerks',
    'Postal Service Mail Carriers',
    'Postal Service Mail Sorters, Processors, and Processing Machine Operators',
    'Postal Service Workers',
    'Postmasters and Mail Superintendents',
    'Postsecondary Teachers',
    'Pourers and Casters, Metal',
    'Power Distributors and Dispatchers',
    'Power Plant Operators',
    'Power Plant Operators, Distributors, and Dispatchers',
    'Precision Instrument and Equipment Repairers',
    'Prepress Technicians and Workers',
    'Preschool and Kindergarten Teachers',
    'Preschool Teachers, Except Special Education',
    'Preschool, Primary, Secondary, and Special Education School Teachers',
    'Pressers, Textile, Garment, and Related Materials',
    'Print Binding and Finishing Workers',
    'Printing Press Operators',
    'Printing Workers',
    'Private Detectives and Investigators',
    'Probation Officers and Correctional Treatment Specialists',
    'Procurement Clerks',
    'Producers and Directors',
    'Production Occupations',
    'Production, Planning, and Expediting Clerks',
    'Proofreaders and Copy Markers',
    'Property, Real Estate, and Community Association Managers',
    'Prosthodontists',
    'Protective Service Occupations',
    'Psychiatric Aides',
    'Psychiatric Technicians',
    'Psychiatrists',
    'Psychologists',
    'Psychology Teachers, Postsecondary',
    'Public Address System and Other Announcers',
    'Public Relations and Fundraising Managers',
    'Public Relations Specialists',
    'Pump Operators, Except Wellhead Pumpers',
    'Pumping Station Operators',
    'Purchasing Agents, Except Wholesale, Retail, and Farm Products',
    'Purchasing Managers',
    'Radiation Therapists',
    'Radio and Telecommunications Equipment Installers and Repairers',
    'Radio and Television Announcers',
    'Radio Operators',
    'Radio, Cellular, and Tower Equipment Installers and Repairers',
    'Radiologic Technologists',
    'Rail Car Repairers',
    'Rail Transportation Workers',
    'Rail Yard Engineers, Dinkey Operators, and Hostlers',
    'Railroad Brake, Signal, and Switch Operators',
    'Railroad Conductors and Yardmasters',
    'Rail-Track Laying and Maintenance Equipment Operators',
    'Real Estate Brokers',
    'Real Estate Brokers and Sales Agents',
    'Real Estate Sales Agents',
    'Receptionists and Information Clerks',
    'Recreation and Fitness Studies Teachers, Postsecondary',
    'Recreation and Fitness Workers',
    'Recreation Workers',
    'Recreational Therapists',
    'Recreational Vehicle Service Technicians',
    'Refractory Materials Repairers, Except Brickmasons',
    'Refuse and Recyclable Material Collectors',
    'Registered Nurses',
    'Rehabilitation Counselors',
    'Reinforcing Iron and Rebar Workers',
    'Religious Workers',
    'Reporters and Correspondents',
    'Reservation and Transportation Ticket Agents and Travel Clerks',
    'Residential Advisors',
    'Respiratory Therapists',
    'Respiratory Therapy Technicians',
    'Retail Sales Workers',
    'Retail Salespersons',
    'Riggers',
    'Rock Splitters, Quarry',
    'Rolling Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Roof Bolters, Mining',
    'Roofers',
    'Rotary Drill Operators, Oil and Gas',
    'Roustabouts, Oil and Gas',
    'Sailors and Marine Oilers',
    'Sales and Related Occupations',
    'Sales Engineers',
    'Sales Managers',
    'Sales Representatives, Services',
    'Sales Representatives, Wholesale and Manufacturing',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Sawing Machine Setters, Operators, and Tenders, Wood',
    'Secondary School Teachers',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Secretaries and Administrative Assistants',
    'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Security and Fire Alarm Systems Installers',
    'Security Guards',
    'Security Guards and Gaming Surveillance Officers',
    'Segmental Pavers',
    'Self-Enrichment Education Teachers',
    'Semiconductor Processors',
    'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Te',
    'Septic Tank Servicers and Sewer Pipe Cleaners',
    'Service Unit Operators, Oil, Gas, and Mining',
    'Set and Exhibit Designers',
    'Sewers, Hand',
    'Sewing Machine Operators',
    'Shampooers',
    'Sheet Metal Workers',
    'Ship and Boat Captains and Operators',
    'Ship Engineers',
    'Shipping, Receiving, and Traffic Clerks',
    'Shoe and Leather Workers',
    'Shoe and Leather Workers and Repairers',
    'Shoe Machine Operators and Tenders',
    'Signal and Track Switch Repairers',
    'Skincare Specialists',
    'Slaughterers and Meat Packers',
    'Slot Supervisors',
    'Small Engine Mechanics',
    'Social and Community Service Managers',
    'Social and Human Service Assistants',
    'Social Science Research Assistants',
    'Social Sciences Teachers, Postsecondary',
    'Social Scientists and Related Workers',
    'Social Work Teachers, Postsecondary',
    'Social Workers',
    'Sociologists',
    'Sociology Teachers, Postsecondary',
    'Software Developers and Programmers',
    'Software Developers, Applications',
    'Software Developers, Systems Software',
    'Soil and Plant Scientists',
    'Solar Photovoltaic Installers',
    'Sound Engineering Technicians',
    'Special Education Teachers',
    'Special Education Teachers, Kindergarten and Elementary School',
    'Special Education Teachers, Middle School',
    'Special Education Teachers, Preschool',
    'Special Education Teachers, Secondary School',
    'Speech-Language Pathologists',
    'Stationary Engineers and Boiler Operators',
    'Statistical Assistants',
    'Statisticians',
    'Stock Clerks and Order Fillers',
    'Stonemasons',
    'Structural Iron and Steel Workers',
    'Structural Metal Fabricators and Fitters',
    'Substance Abuse and Behavioral Disorder Counselors',
    'Substitute Teachers',
    'Subway and Streetcar Operators',
    'Supervisors of Food Preparation and Serving Workers',
    'Supervisors of Personal Care and Service Workers',
    'Supervisors of Protective Service Workers',
    'Supervisors of Transportation and Material Moving Workers',
    'Surgeons',
    'Surgical Technologists',
    'Survey Researchers',
    'Surveying and Mapping Technicians',
    'Surveyors',
    'Surveyors, Cartographers, and Photogrammetrists',
    'Switchboard Operators, Including Answering Service',
    'Tailors, Dressmakers, and Custom Sewers',
    'Tailors, Dressmakers, and Sewers',
    'Tank Car, Truck, and Ship Loaders',
    'Tapers',
    'Tax Examiners and Collectors, and Revenue Agents',
    'Tax Examiners, Collectors and Preparers, and Revenue Agents',
    'Tax Preparers',
    'Taxi Drivers and Chauffeurs',
    'Teacher Assistants',
    'Team Assemblers',
    'Technical Writers',
    'Telecommunications Equipment Installers and Repairers, Except Line Installers',
    'Telecommunications Line Installers and Repairers',
    'Telemarketers',
    'Telephone Operators',
    'Television, Video, and Motion Picture Camera Operators and Editors',
    'Tellers',
    'Terrazzo Workers and Finishers',
    'Textile Bleaching and Dyeing Machine Operators and Tenders',
    'Textile Cutting Machine Setters, Operators, and Tenders',
    'Textile Knitting and Weaving Machine Setters, Operators, and Tenders',
    'Textile Machine Setters, Operators, and Tenders',
    'Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders',
    'Textile, Apparel, and Furnishings Workers',
    'Therapists',
    'Tile and Marble Setters',
    'Timing Device Assemblers and Adjusters',
    'Tire Builders',
    'Tire Repairers and Changers',
    'Title Examiners, Abstractors, and Searchers',
    'Tool and Die Makers',
    'Tool Grinders, Filers, and Sharpeners',
    'Top Executives',
    'Tour and Travel Guides',
    'Tour Guides and Escorts',
    'Traffic Technicians',
    'Training and Development Managers',
    'Training and Development Specialists',
    'Transit and Railroad Police',
    'Transportation and Material Moving Occupations',
    'Transportation Attendants, Except Flight Attendants',
    'Transportation Inspectors',
    'Transportation Security Screeners',
    'Transportation, Storage, and Distribution Managers',
    'Travel Agents',
    'Travel Guides',
    'Tree Trimmers and Pruners',
    'Umpires, Referees, and Other Sports Officials',
    'Upholsterers',
    'Urban and Regional Planners',
    'Ushers, Lobby Attendants, and Ticket Takers',
    'Vehicle and Mobile Equipment Mechanics, Installers, and Repairers',
    'Veterinarians',
    'Veterinary Assistants and Laboratory Animal Caretakers',
    'Veterinary Technologists and Technicians',
    'Vocational Education Teachers, Postsecondary',
    'Waiters and Waitresses',
    'Watch Repairers',
    'Water and Wastewater Treatment Plant and System Operators',
    'Water Transportation Workers',
    'Web Developers',
    'Weighers, Measurers, Checkers, and Samplers, Recordkeeping',
    'Welders, Cutters, Solderers, and Brazers',
    'Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders',
    'Welding, Soldering, and Brazing Workers',
    'Wellhead Pumpers',
    'Wholesale and Retail Buyers, Except Farm Products',
    'Wind Turbine Service Technicians',
    'Woodworkers',
    'Woodworking Machine Setters, Operators, and Tenders',
    'Woodworking Machine Setters, Operators, and Tenders, Except Sawing',
    'Word Processors and Typists',
    'Writers and Authors',
    'Writers and Editors',
    'Zoologists and Wildlife Biologists'
];

exports.getOccupations = function() {
    return occupationsList;
};
